CREATE TABLE Client(
    ID SERIAL PRIMARY KEY NOT NULL,
    Name VARCHAR NOT NULL
);


CREATE TABLE Item(
    ID SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR NOT NULL,
    price real NOT NULL
);

CREATE TABLE Invoice(
    ID SERIAL PRIMARY KEY NOT NULL,
    Date DATE NOT NULL,
    ClientID INT NOT NULL REFERENCES Client(ID),
    ItemID INT NOT NULL REFERENCES Item(ID),
    Qty INT NOT NULL,
    Location VARCHAR(2) NOT NULL,
    name VARCHAR NOT NULL
);

SELECT
